version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: marketguru_postgres

    ports:
      - '5432:5432'

    env_file:
      - .env.development
      - .env.production

    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
